org.gradle.jvmargs=-Xmx1024m -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError -XX:+UseG1GC -XX:MaxGCPauseMillis=200
android.useAndroidX=true
android.enableOnDemandConfiguration=true
org.gradle.parallel=false
org.gradle.daemon=false
org.gradle.configureondemand=true
android.disableBuildFeaturesByDefault=true
android.defaults.buildfeatures.aidl=false
android.defaults.buildfeatures.buildconfig=false
